services:
    api.user_provider:
        class: ApiBundle\Security\ApiUserProvider
        arguments: ["@doctrine.orm.entity_manager"]
        public: false

    api.auth_token_authenticator:
        class:     ApiBundle\Security\UserAuthTokenAuthenticator
        arguments: ["@security.http_utils"]
        public:    false

    api.invoice.event_listener:
        class: ApiBundle\EventListener\InvoiceListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    api.user.event_listener:
        class: ApiBundle\EventListener\UserListener
        arguments: ["@security.password_encoder"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
