services:
    api.invoice.event_listener:
        class: ApiBundle\EventListener\InvoiceListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    api.user.event_listener:
        class: ApiBundle\EventListener\UserListener
        arguments: ["@security.password_encoder"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
