<?php

namespace ApiBundle\Repository;

/**
 * InvoiceStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
