ApiBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: false
        username:
            expose: true
            groups: [user, auth-token]
        firstname:
            expose: true
            groups: [user, auth-token]
        lastname:
            expose: true
            groups: [user, auth-token]
        email:
            expose: true
            groups: [user, auth-token]
        password:
            expose: false
        plainPassword:
            expose: false
        token:
            expose: false
